drop table if exists member CASCADE;
create table member
(
    id bigint generated by default as identity, //id : Long->BigInt타입, 그 이후~~ : null 값ㅇ르 db가 자동으로 채워줌
    name varchar(255),
    primary key (id)

);

